dist: trusty
sudo: false
addons:
  postgresql: "9.5"
language: python
python:
- '3.6'
git:
  depth: false
branches:
  only:
  - master
  - develop
  - feature/basic-testing
  - /^[0-9]+/
stages:
  - name: testing
  - name: deploying

jobs:
  include:
    - stage: testing
      install:
        - pip install -c constraints.txt -r requirements.txt
        - pip install -c constraints.txt -e .
      script:
        - flake8
        - black --check print-logs run-query setup.py ethindex tests
        - mypy --ignore-missing-imports ethindex tests
        - pytest tests

    - stage: deploying
      name: docker
      env:
        - DOCKER_USER=trustlinesautomation
        # DOCKER_PASSWORD
        - secure: "k8t/q0Mns5eD4XEqkccSDuHoluxMM6pbsKvDTNd/GMg98nFZWPDu+EQLIjpzmaq/ZNrym+pVufDWkn1kByWCuKBHF+pW5he2amRmmOfnEU/VuSAeDnNSxoXiLwjFMW6O005rz84H+832/4/HKZe4TMQdquAj1Ks7mrbG4L8LYR01x13eC6rbycaBmy1UQQ8keGOLVSiL6t5X87lQ3e96ae5TIbzSb+2OD2h5URE6Vu4DCxfpijyMIrG5A2kLtIEHqNFmEBWlOdWIH+hIZOWFIUPUXeF2LN5G9YNKWjaQB1hhCv6mY0bQK/duUZt3QXjFXVuoBffOQpFDC6tthrweARPfSgG7bZlvgSs1oEzG0XVtHvLof5PoQJHlKTriY+vJV6gXUbhyE2SryqfUydJGIoAwrx0UC7yzeUdROhEmxFQcHstNbQjPmPP9Fr49Hbaxsqx5uGs5t4chBv/cAaKOAjthD2gKmgZV3mhKHjEV/cp8gt+cLHzCqxmV2yY/eXD3F+wdkQfFiGubd+wzJo6GcNFfRYqSuLJY4pxnPMX/q9s3TJ44GGQLvw6prDSGRUq6B++8KGH5k7iX5OwLu2X1O+DLYuji54Yk7/alpoic8/LyTvfQknM7DCiPLSIrMxKw70kqC212UCtejmmpFtfB6WonKtSQ54kYJJsW3Pbv39w="

      install: /bin/true
      sudo: true
      service: docker
      script:
        - docker build -t ethindex .
      deploy:
        skip_cleanup: true
        provider: script
        script: ".travis/push-docker-image"
        on:
          all_branches: true
          condition: $TRAVIS_BRANCH =~ ^(develop|[0-9]+.*)$
    - stage: deploying
      name: pypi
      install: /bin/true
      script:
        - /bin/true
      deploy:
        - provider: pypi
          skip_cleanup: true
          user: trustlines
          password:
            secure: "KMLwMFp4GMKNy2kzlzBslK3f1E23rTPPz7/mwvfyEKfFLUfutp4AbxzVv0EtEgdeNnKYA1AerNQrpiZcwj1AXlzdLAKG0LMO1leoY6WSJv0o/IeBh0Te4g9KJXmH0w24j+20nF6Z22YtwCQDl0sgUZ2HQxITRg+K0hpcurfWNs4ZbGGnR8tDEN//cnQFDG/pvH4EfmQzXezC4TyzvcnkS17evuEzmzvBP49PhbrHdamVuP5ykxDVzBgcCfsvBcCuLYDY/Pjho66VgaJpyaNgzJexEi28yScZCf/YtgqqWirkTqJe02QrvMin1p0Rj5VlYavWhhR1xP2PW5CGCaGBffUpDmPxXywJTUaIRlBILPsRqzzmjmQUreO6J8Zzg3CENok7yCYx+5D4jUP7/1CHWQvKWxI4dr2UvRzgSnhr3rnW+8hJx1/ley481hEtZYgz8/POlq/Uq4LXn0jT2dUOiwO/K/QPL4LpvZAhaKxymZjbX3brcnpvBbvgKXHbZr7p0vGWBl75GI6QcvB4wKknIE2tlzAjEO6Zpm+9axzkGC6I97eXkDcIvkIufvwB4RoamLccKMRV+B7OblGEbyEmjIJuIuSHIvLYv75dhfjqpJIyV/JX06Q4OQ/dwEbXFJ4l+fL4ywrDTkmN3KDX9G6StIvqzHk4Iccv5fIeDeaSE6k="
          on:
            all_branches: true
            condition: $TRAVIS_BRANCH =~ ^([0-9]+.*)$
