sudo: required
services:
- docker
language: python
python:
- '3.6'
git:
  depth: false
install:
# install from requirements first, because that installs the non-binary psycopg2
  - pip install -c constraints.txt -r requirements.txt
  - pip install -c constraints.txt -e .
script:
- flake8
- black --check print-logs run-query setup.py ethindex
- mypy --ignore-missing-imports ethindex
- docker build -t ethindex .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
deploy:
  skip_cleanup: true
  provider: script
  script: bash docker_push
  on:
    branch: develop
branches:
  only:
  - master
  - develop
env:
  global:
  - secure: LdXqHiqSc+TpcZf+51TJmP1KnGE1fFpuS+Cc7mAUWblyaUPAupVwGZf4Kqyvbk35NGd7AYln+FXWp+oSjbYUYT/UnIo/NaBLRqwB8zaFUlsIUoUs4cJpDoPMzxJ7PIronsTit5t71xd5e/U20jS+zQiBbt8zQkIQ6qgDl4itGV+FTxPP0fcSSFJ9+QTzyKZRC9XU19DQxLXrAqvE8bbUK3m8iXDVRXEGjsbVJf2PuZD5rt3jnFHEdIBOVP2qeTMHnNojSlN26y2c5aUoHE2VPtGBFv5BFvq35k8jnQIouGaE0ZKGFp1r3L5+ZLDofnyGAejjHaMDMzwBJ94mP0JD7WuhbCyiykBg/7+DryLQv8aJ2P/UH+IDn4AbILVRBh2z7PFy7UyZ7dxZvdG7+LbHlnThtS+ItnBUlW2cwgdu7v6fP7iVkv0FotCNAAx4VANI61XYv+FqAs4ZzTcRX8rSppMs+uOh3LX86NJpMB0OjPv0ITd1kuG+7RIoM+hW17jKjgbYkpFPI09URKL/wUdCD17FQ2eWoqVODA7OTzArRB//yubS0SRTjEn/c+ajXo6mtKPRHwZ5y2OywUhu/JxF5TXXKkdKhdskx3hneFMQKtU/lbhZjD5vJYSjEX9roJSsvs8gaIB4VaKOHE1t+YPLUfvEDpTVO45JFB35Cu06QSU=
  - secure: YcaO6L1cceu28CxQoU2p4ZlVLi5J0awhuCKoQuQmFpFE8riBBL8USwlp6AfEyhOm5rYBkDagINmr9xFMyMmTgyE6Q+KxL/u+QRVBmeUnJpVLRdWwaxbkx9AJ915278DFKXPrgmphcOiHBgi5cCB+hzOM3U8CpLlFIA1twWDLAB2+ydaRM4BJUrE6HoOg5j4NK/svXP4qbrLJovaoKgFVkCgcVamVScYUwAr4BxYfZ1IJFVNAX1QKe+FHG79dIAlYUx9DP6bizwkDGLD+fGTgzpQMG/gL8WoKQK+gi2+exRjZ/zXcpQONO5lQJ3oizA1cCuLR76DFEcEuMPJD6NcDVhqpr9CXgsfCepJViN5P2xVO0oHRupYGMOg8YnS4OJJXZbcYwbm6EhZ93VpsANf+HQu0S++cq7lUx7LWSHU4mNr+DGVXUBjIpVfNjjFJiZxQlesgqNknWk6KcmQPZp6XSKzpI4plnYcG3bQe+TLpFXu5X6BftNRusdtsH5lC7UDwd6H+oFxr/FoOrnhcyWNio93TFoWmdW6Y+90J7DlKThlBoH7RbPaWq8c7pE6IHZDgHDgH81+UbDQdfMZf60l4c32qdBgFTMD8vRNKwLRNW5Z/b5ziMxnhar1uS7Z6G9GP+y3nw8lGPaXsYdEq8V0qyYEAGxndx57/XNj3BrDENA4=
