sudo: required
services:
- docker
language: python
python:
- '3.6'
git:
  depth: false
install:
- pip install -c constraints.txt -r requirements.txt
- pip install -c constraints.txt -e .
script:
- flake8
- black --check print-logs run-query setup.py ethindex
- mypy --ignore-missing-imports ethindex
- docker build -t ethindex .
- echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USER" --password-stdin
deploy:
  skip_cleanup: true
  provider: script
  script: ".travis/push-docker-image"
  on:
    branch: develop
branches:
  only:
  - master
  - develop
env:
  global:
  - DOCKER_USER=trustlinesautomation
  - secure: GTyUyC7fNPYFwoNxGut8nlgTWxTm1HiAi+IBSIi2DnUbGHl7/TUp4BZeqNED5tsasM99Zv2A2/UlqbuIKiJbXKG2Dy0z+ZG+wpjK0q5KD/6SzllrGP0Eh4sPA73fd2MIKJBZx1CGTZiSUqcY4Ryhf8U4KMDM+L5aBEw14nrrfs3nKdcfnDnzzzPMZCbjLkJW6ULcqtQx5nomJPZuylBwHKoH6NW+PRNDq/NUrQH6waFfEPM46tZ2tV+i5JeojqQgO6Vw98vikCXa9pZbQzMXk7aJglJ1a5pCrFaZ5pZm7XpFK5X4yTwg7fA5FkgtJdLbrLNoGVCNW/lVXpUpsvKyS596Hk5grUt23HX9MUHUzT243wA+g7CByXlS8nQ0ymWdBnDCE9tClHjqIGHlNjkZNgBHYAvdvnx6i5kp7j7V1ZFnIy2wHiBbruyydFXt4cy+/KkROYzWRkn7w113s0EUvwJWpeJ6//Mufp/2pu0TR9o0iFHlZLMJQX8rtlKBGZ6WE8HEcdXCkjKvf0CUwB/yqr34kefouKJ3cp54rWfOVGo0TkucwPmKCae2CcInrAyjCq8LyBRHV07c4qVqat/Sz6rLwGGJWX8Xr37iTnAhQSQfZf25/c0PrkxPLhTH8XQTTgaVZ8L8xOtwpdxybEjkueDu9wIX23lHEDrZK0ZG9fA=
